"""Playwright authentication script for SecScan.

Generated by: secscan init --target juice-shop

HOW THIS SCRIPT WORKS
=====================
SecScan calls this script before a scan begins (and again whenever a session
expires mid-scan).  Your job is to:

  1. Launch a browser via the provided `page` object.
  2. Perform the full login flow — fill forms, click buttons, handle OTPs.
  3. Return nothing.  SecScan captures cookies and localStorage automatically
     after this function returns.

SecScan passes in a Playwright `Page` that is already open and pointed at
`base_url` (from secscan.toml).  You do not need to call browser.new_page()
or page.goto() to start.  You can and should call page.goto() to navigate to
the login page.

PARAMETERS
==========
  page (playwright.async_api.Page):
      The browser page object.  Use standard Playwright API calls.
  config (secscan.config.Config):
      The loaded config for this target.  Useful for reading base_url.

RETURNS
=======
  None.  Do not return anything.  SecScan captures the session state after
  this coroutine completes.

ERROR HANDLING
==============
  Raise an exception if login fails.  SecScan will mark the session as dead
  and stop the scan rather than silently continue with an invalid session.
  A clear exception message helps the operator understand what went wrong.

EXAMPLES
========
See the commented sections below for common auth patterns:
  - Username + password form
  - OTP (email/SMS) flow
  - Razorpay or other payment provider sign-in
  - Cookie injection (manual fallback when scripting the login is too hard)

"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from playwright.async_api import Page
    from secscan.config import Config


async def authenticate(page, config):
    await page.goto("http://localhost:3000/#/login", wait_until="networkidle")

    # Dismiss Juice Shop's Material welcome/cookie overlays before login.
    try:
        await page.click('button[aria-label="dismiss cookie message"]', timeout=1500)
    except Exception:
        pass
    try:
        await page.click('.mat-dialog-container button', timeout=1500)
    except Exception:
        pass

    await page.fill('input[name="email"]', 'admin@juice-sh.op')
    await page.fill('input[name="password"]', 'admin123')

    try:
        await page.keyboard.press("Escape")
    except Exception:
        pass

    await page.click('button[type="submit"]')
    await page.wait_for_load_state("networkidle")
