"""Playwright authentication script for SecScan.

Generated by: secscan init --target test-target

HOW THIS SCRIPT WORKS
=====================
SecScan calls this script before a scan begins (and again whenever a session
expires mid-scan).  Your job is to:

  1. Launch a browser via the provided `page` object.
  2. Perform the full login flow — fill forms, click buttons, handle OTPs.
  3. Return nothing.  SecScan captures cookies and localStorage automatically
     after this function returns.

SecScan passes in a Playwright `Page` that is already open and pointed at
`base_url` (from secscan.toml).  You do not need to call browser.new_page()
or page.goto() to start.  You can and should call page.goto() to navigate to
the login page.

PARAMETERS
==========
  page (playwright.async_api.Page):
      The browser page object.  Use standard Playwright API calls.
  config (secscan.config.Config):
      The loaded config for this target.  Useful for reading base_url.

RETURNS
=======
  None.  Do not return anything.  SecScan captures the session state after
  this coroutine completes.

ERROR HANDLING
==============
  Raise an exception if login fails.  SecScan will mark the session as dead
  and stop the scan rather than silently continue with an invalid session.
  A clear exception message helps the operator understand what went wrong.

EXAMPLES
========
See the commented sections below for common auth patterns:
  - Username + password form
  - OTP (email/SMS) flow
  - Razorpay or other payment provider sign-in
  - Cookie injection (manual fallback when scripting the login is too hard)

"""

from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from playwright.async_api import Page
    from secscan.config import Config


async def authenticate(page: "Page", config: "Config") -> None:
    """Perform the full login flow for test-target.

    Edit this function.  The implementation below is a starter template for
    a standard username + password form.  Adapt it to the actual login flow.

    Args:
        page:   Playwright page, already navigated to config.target.base_url.
        config: SecScan config for this target.
    """
    base_url = config.target.base_url

    # ------------------------------------------------------------------
    # EXAMPLE A: Standard username / password form
    # Uncomment and adapt.
    # ------------------------------------------------------------------
    # await page.goto(f"{base_url}/login")
    # await page.fill("#email", "pentester@example.com")
    # await page.fill("#password", "your-test-password")
    # await page.click('button[type="submit"]')
    # await page.wait_for_url("**/dashboard**", timeout=10_000)
    # # Verify login succeeded — raise if not.
    # if "/login" in page.url:
    #     raise RuntimeError(f"Login failed — still on {page.url}")

    # ------------------------------------------------------------------
    # EXAMPLE B: OTP flow (email or SMS)
    # The hardest part is reading the OTP.  Options:
    #   - Use a test account with a fixed OTP (if the app supports this).
    #   - Read the OTP from a local mailbox (mailhog, etc.).
    #   - Read from a shared Slack channel or email alias.
    # ------------------------------------------------------------------
    # await page.goto(f"{base_url}/login")
    # await page.fill("#phone", "+91-9876543210")
    # await page.click("#send-otp")
    # await page.wait_for_selector("#otp-input", timeout=15_000)
    # otp = await _get_otp_from_email()   # implement this helper
    # await page.fill("#otp-input", otp)
    # await page.click("#verify-otp")
    # await page.wait_for_url("**/dashboard**", timeout=10_000)

    # ------------------------------------------------------------------
    # EXAMPLE C: Cookie injection fallback
    # Use this when automating the login flow is not feasible (e.g., the
    # login page has CAPTCHA, hardware key, or SMS OTP with no test bypass).
    # Steps:
    #   1. Log in manually in your browser.
    #   2. Export the session cookies (DevTools → Application → Cookies).
    #   3. Paste them below.  Re-export when they expire.
    # ------------------------------------------------------------------
    # await page.context.add_cookies([
    #     {
    #         "name":   "session",
    #         "value":  "PASTE_YOUR_SESSION_COOKIE_HERE",
    #         "domain": "example.com",
    #         "path":   "/",
    #         "secure": True,
    #         "httpOnly": True,
    #     },
    # ])
    # await page.goto(f"{base_url}/dashboard")
    # if "/login" in page.url:
    #     raise RuntimeError("Injected cookies are expired — refresh them.")

    # ------------------------------------------------------------------
    # PLACEHOLDER — replace with real auth logic before running a scan.
    # ------------------------------------------------------------------
    raise NotImplementedError(
        "Edit targets/test-target/auth_script.py to implement the login flow. "
        "See the commented examples in the file for guidance."
    )
